### PR TITLE
Found outdated code, sorry!

### PR DESCRIPTION
**Pull request by sduncan-nyt**

### CODE REVIEW

**Comment by sduncan-nyt** [comment]
@oliver006 so sorry about that, long day 😬

**Comment by oliver006** [comment]
All good :-)

This looks good - can you rebase off of master please?

**Comment by sduncan-nyt** [comment]
Rebased and tests are passing!

**Comment by oliver006** [comment]
:+1:

**Comment by oliver006** [comment]
Released as 1.8.1

**Pull request merged**
