### PR TITLE
Added support for gen2 functions

### LINKED ISSUE #28: Add support for Google Functions 2nd Generation: --gen2 parameter
Google Functions 2nd generation was GA'd on Aug 9, 2022. To use this, the `gcloud functions deploy` command needs a `--gen2` parameter added.

Docs: https://cloud.google.com/sdk/gcloud/reference/functions/deploy#--gen2

### PR DESCRIPTION
**Pull request by konrness**
Resolves #28

### CODE REVIEW

**Comment by konrness** [comment]
Don't merge yet, I'm testing.

**Comment by konrness** [comment]
Tested successfully now that I updated Cloud SDK version. 👍

**Review by oliver006 — APPROVED** [review]
🏖️

**Comment by oliver006** [comment]
Looks good - thanks!

**Pull request merged**
