### PR TITLE
Switching --allow-unauthenticated from string to bool

### PR DESCRIPTION
**Pull request by sduncan-nyt**
In working with this new flag, we thought it would be better as a bool than a str. It better fits the use of the flag, either it's included or not, and seems more intuitive.

### CODE REVIEW

**Comment by oliver006** [comment]
@sduncan-nyt - this broke the build, can you please check what happened?

https://cloud.drone.io/oliver006/drone-gcf/227/1/2

PS: I'll check why PRs don't trigger a drone build, not sure why that's not happening.

**Comment by sduncan-nyt** [comment]
Oh sure I'll check, my bad! I thought I ran the tests after the merged, but must have been before

**Comment by oliver006** [comment]
All good, opened https://github.com/oliver006/drone-gcf/pull/12 to fix this.

Oddly enough, it does run drone tests when I opened the PR. Could you maybe try opening a PR and see if it works now? (I toggled a cloud.drone.io setting)

**Comment by sduncan-nyt** [comment]
I made a PR here: https://github.com/oliver006/drone-gcf/pull/13

Doesn't seem to be running tests? Maybe because it's cross forks?

**Comment by oliver006** [comment]
Odd, coul.d be the fork, not sure why it doesn't run the tests, event filter says "push" which should do the trick?

**Pull request merged**
