### PR TITLE
--service-account parameter support

### PR DESCRIPTION
**Pull request by aromaniuk-postclick**

### CODE REVIEW

**Comment by oliver006** [comment]
Thanks for the PR, looks good!
Can you please add a test for the new parameter and then this should be good to go.

**Comment by aromaniuk-postclick** [comment]
Hi!
I've just added a test for this but for some reason tests are marked as failed (all passed). Is the code coverage too low?

**Comment by oliver006** [comment]
I think the test fails due to your code not being "go fmt" formatted?

**Comment by aromaniuk-postclick** [comment]
Oh! You're probably right :)

**Review by oliver006 — APPROVED** [review]
Nice work!

**Comment by aromaniuk-postclick** [comment]
Cheers!
Thanks for merging :)

**Comment by oliver006** [comment]
👍 

Released as [v1.10.0](https://github.com/oliver006/drone-gcf/releases/tag/v1.10.0)

**Pull request merged**
